"""
ReportLab PDF Analysis Report Service
-------------------------------------
Generates professional academic PDF analysis reports incorporating patient metadata,
CT images, subtype classification probabilities, Grad-CAM heatmaps, and disclaimers.
"""

import os
import json
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage, HRFlowable

def generate_pdf_report(patient, prediction, ct_image_path, gradcam_path, output_pdf_path):
    """
    Generates a PDF analysis report for a patient's CT scan prediction.
    """
    os.makedirs(os.path.dirname(output_pdf_path), exist_ok=True)
    doc = SimpleDocTemplate(output_pdf_path, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    story = []

    styles = getSampleStyleSheet()

    # Custom Styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#1e3a8a'),
        alignment=0
    )
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#475569')
    )
    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        parent=styles['Normal'],
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#991b1b'),
        backColor=colors.HexColor('#fef2f2'),
        borderPadding=6
    )
    heading2_style = ParagraphStyle(
        'Heading2Custom',
        parent=styles['Heading2'],
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#0f172a'),
        spaceBefore=10,
        spaceAfter=6
    )

    # 1. Header
    story.append(Paragraph("AUTOMATED LUNG CANCER SUBTYPE CLASSIFICATION REPORT", title_style))
    story.append(Paragraph("AI-Assisted Decision-Support System | PyTorch Deep CNN + CBAM Attention Engine", subtitle_style))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#1e3a8a'), spaceAfter=10))

    # 2. Disclaimer Banner
    disclaimer_text = "<b>RESEARCH & DECISION-SUPPORT DISCLAIMER:</b> This report is generated by an automated AI decision-support research system and is NOT intended as a definitive medical diagnostic device. All findings must be clinically evaluated by a qualified radiologist."
    story.append(Paragraph(disclaimer_text, disclaimer_style))
    story.append(Spacer(1, 12))

    # 3. Patient Information Table
    patient_data = [
        [Paragraph("<b>Patient Code:</b>", styles['Normal']), Paragraph(patient.patient_code, styles['Normal']),
         Paragraph("<b>Analysis Date:</b>", styles['Normal']), Paragraph(datetime.now().strftime("%Y-%m-%d %H:%M"), styles['Normal'])],
        [Paragraph("<b>Full Name:</b>", styles['Normal']), Paragraph(patient.full_name, styles['Normal']),
         Paragraph("<b>Age / Gender:</b>", styles['Normal']), Paragraph(f"{patient.age} / {patient.gender}", styles['Normal'])],
        [Paragraph("<b>Model Version:</b>", styles['Normal']), Paragraph(prediction.model_version, styles['Normal']),
         Paragraph("<b>Predicted Subtype:</b>", styles['Normal']), Paragraph(f"<b>{prediction.predicted_subtype}</b>", styles['Normal'])]
    ]

    patient_table = Table(patient_data, colWidths=[110, 160, 110, 160])
    patient_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#cbd5e1')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(patient_table)
    story.append(Spacer(1, 15))

    # 4. Probabilities Table
    story.append(Paragraph("Subtype Probability Breakdown", heading2_style))
    probs_dict = json.loads(prediction.probabilities_json) if isinstance(prediction.probabilities_json, str) else prediction.probabilities_json

    prob_rows = [["Subtype Class Name", "Confidence Score", "Probability Bar"]]
    for k, v in probs_dict.items():
        pct = v * 100
        bar = "█" * int(pct // 5)
        prob_rows.append([k, f"{pct:.2f}%", bar])

    prob_table = Table(prob_rows, colWidths=[200, 120, 220])
    prob_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1e293b')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('PADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(prob_table)
    story.append(Spacer(1, 15))

    # 5. Visual Explanations (Grad-CAM & Original CT)
    story.append(Paragraph("Visual Explanation (Grad-CAM Spatial Attention Heatmap)", heading2_style))
    
    img_cells = []
    if os.path.exists(ct_image_path):
        img_cells.append(RLImage(ct_image_path, width=220, height=220))
    else:
        img_cells.append(Paragraph("CT Image Not Available", styles['Normal']))

    if gradcam_path and os.path.exists(gradcam_path):
        img_cells.append(RLImage(gradcam_path, width=220, height=220))
    else:
        img_cells.append(Paragraph("Grad-CAM Image Not Available", styles['Normal']))

    img_table = Table([[img_cells[0], img_cells[1]]], colWidths=[270, 270])
    img_table.setStyle(TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(img_table)
    story.append(Spacer(1, 15))

    # Footer
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#cbd5e1'), spaceAfter=6))
    story.append(Paragraph("Generated by Automated Lung Cancer Subtype Classification Research Platform", subtitle_style))

    doc.build(story)
    return output_pdf_path
